//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public Claim()
        {
            this.ClaimForms = new HashSet<ClaimForm>();
            this.ClaimInjuryDetails = new HashSet<ClaimInjuryDetail>();
            this.ClaimNotes = new HashSet<ClaimNote>();
            this.ClaimPolicyNotes = new HashSet<ClaimPolicyNote>();
            this.ClaimPolicyAgents = new HashSet<ClaimPolicyAgent>();
            this.ClaimRecoveries = new HashSet<ClaimRecovery>();
            this.OshaDetails = new HashSet<OshaDetail>();
            this.ClaimOtherServices = new HashSet<ClaimOtherService>();
            this.ClaimServices = new HashSet<ClaimService>();
            this.ClaimSubLimits = new HashSet<ClaimSubLimit>();
            this.ICD9Codes = new HashSet<ICD9Codes>();
            this.ClaimExpenses = new HashSet<ClaimExpense>();
            this.IndemnityWageComps = new HashSet<IndemnityWageComp>();
            this.ClaimFROIs = new HashSet<ClaimFROI>();
            this.ClaimSROIs = new HashSet<ClaimSROI>();
            this.Medicals = new HashSet<Medical>();
            this.ClaimCreditMemoes = new HashSet<ClaimCreditMemo>();
            this.ClaimViewPermissions = new HashSet<ClaimViewPermission>();
            this.Invoices = new HashSet<Invoice>();
            this.ReinsurerClaims = new HashSet<ReinsurerClaim>();
            this.ClaimantNotes = new HashSet<ClaimantNote>();
            this.ClaimantPhotoes = new HashSet<ClaimantPhoto>();
            this.ClaimActivityLogs = new HashSet<ClaimActivityLog>();
            this.FolderStructures = new HashSet<FolderStructure>();
            this.FolderStructures1 = new HashSet<FolderStructure>();
            this.FolderStructures2 = new HashSet<FolderStructure>();
            this.ClaimCoverages = new HashSet<ClaimCoverage>();
            this.ICD10Codes = new HashSet<ICD10Codes>();
            this.ClaimDiaries = new HashSet<ClaimDiary>();
            this.ClaimantDetails = new HashSet<ClaimantDetail>();
            this.ClaimEmails = new HashSet<ClaimEmail>();
            this.LegalContacts = new HashSet<LegalContact>();
            this.ClaimEmployerDetails = new HashSet<ClaimEmployerDetail>();
            this.LienHolders = new HashSet<LienHolder>();
            this.ClaimLegals = new HashSet<ClaimLegal>();
            this.ClaimDocuments = new HashSet<ClaimDocument>();
            this.ClaimPhotoes = new HashSet<ClaimPhoto>();
            this.ClaimWriteChecks = new HashSet<ClaimWriteCheck>();
            this.ClaimLossTotals = new HashSet<ClaimLossTotal>();
            this.ClaimReserves = new HashSet<ClaimReserve>();
            this.Section111Detail = new HashSet<Section111Detail>();
        }
    
        public int ClaimID { get; set; }
        public int UserID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> CompanyBranchID { get; set; }
        public Nullable<int> ClientBranchID { get; set; }
        public Nullable<int> BillingProfileID { get; set; }
        public string PolicyNumber { get; set; }
        public string InsurerClaimNumber { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public Nullable<int> ClaimTypeID { get; set; }
        public string PolicyFormType { get; set; }
        public Nullable<int> PolicyTypeID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> InitialCoverageDate { get; set; }
        public string CategoryId { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<int> TypeofLoss { get; set; }
        public string LossDescription { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool FKUsers { get; set; }
        public bool FKClient { get; set; }
        public bool FKPortalBranch { get; set; }
        public bool FKClientBranch { get; set; }
        public bool FKClientBillingProfile { get; set; }
        public bool FKClientContacts { get; set; }
        public bool FKrefClaimType { get; set; }
        public bool FKrefPolicyType { get; set; }
        public bool FKSame { get; set; }
        public Nullable<decimal> AdjCommOverride { get; set; }
        public Nullable<decimal> AdjCommFlatFeeOverride { get; set; }
        public Nullable<int> AdjusterID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public string AdjusterFile { get; set; }
        public Nullable<byte> Severity { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EventNo { get; set; }
        public Nullable<int> PortalID { get; set; }
        public int FKPortal { get; set; }
        public Nullable<int> XactAnalysisID { get; set; }
        public bool FKXactAnalysis { get; set; }
        public string ExcessCarrier { get; set; }
        public Nullable<decimal> RetentionAmt { get; set; }
        public Nullable<decimal> AggregateAmt { get; set; }
        public bool paymentfrozen { get; set; }
        public bool LSS { get; set; }
        public string ClosingClaimMethod { get; set; }
        public Nullable<System.DateTime> interviewComplete { get; set; }
        public Nullable<System.DateTime> AssessmentComplete { get; set; }
        public bool MedicalLiability { get; set; }
        public bool IndemnityLiability { get; set; }
        public Nullable<System.DateTime> FROIDate { get; set; }
        public Nullable<System.DateTime> SROIDate { get; set; }
        public Nullable<System.DateTime> CloseFile { get; set; }
        public Nullable<System.DateTime> FirstReopen { get; set; }
        public Nullable<System.DateTime> ReOpenCompleted { get; set; }
        public Nullable<System.DateTime> FinalClosed { get; set; }
        public Nullable<System.DateTime> LastReported { get; set; }
        public string ExcessClaim { get; set; }
        public bool IsClaimClosed { get; set; }
        public Nullable<System.DateTime> ClaimCloseDate { get; set; }
        public bool IsClaimReOpened { get; set; }
        public Nullable<System.DateTime> ClaimReOpeneDate { get; set; }
        public string ClaimCloseReason { get; set; }
        public string ClaimReopenReason { get; set; }
        public Nullable<int> JurisdictionID { get; set; }
        public bool FKrefTypeOfLoss { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<int> LinkClaimID { get; set; }
        public string RecordFrom { get; set; }
        public bool isWathcList { get; set; }
        public string XactTransactionID { get; set; }
        public string ReceivedFrom { get; set; }
        public bool isXactClaim { get; set; }
        public bool isSendToXact { get; set; }
        public string TimeReceived { get; set; }
        public string TimeReceivedPeriod { get; set; }
    
        public virtual User UserAdjuster { get; set; }
        public virtual refState refState { get; set; }
        public virtual Portal Portal { get; set; }
        public virtual User UserSupervisor { get; set; }
        public virtual ICollection<ClaimForm> ClaimForms { get; set; }
        public virtual ICollection<ClaimInjuryDetail> ClaimInjuryDetails { get; set; }
        public virtual ICollection<ClaimNote> ClaimNotes { get; set; }
        public virtual ICollection<ClaimPolicyNote> ClaimPolicyNotes { get; set; }
        public virtual ICollection<ClaimPolicyAgent> ClaimPolicyAgents { get; set; }
        public virtual ICollection<ClaimRecovery> ClaimRecoveries { get; set; }
        public virtual ICollection<OshaDetail> OshaDetails { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientContact ClientContact { get; set; }
        public virtual PortalBranch PortalBranch { get; set; }
        public virtual refClaimType refClaimType { get; set; }
        public virtual refPolicyType refPolicyType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ClaimOtherService> ClaimOtherServices { get; set; }
        public virtual ICollection<ClaimService> ClaimServices { get; set; }
        public virtual ICollection<ClaimSubLimit> ClaimSubLimits { get; set; }
        public virtual ICollection<ICD9Codes> ICD9Codes { get; set; }
        public virtual ICollection<ClaimExpense> ClaimExpenses { get; set; }
        public virtual ICollection<IndemnityWageComp> IndemnityWageComps { get; set; }
        public virtual ICollection<ClaimFROI> ClaimFROIs { get; set; }
        public virtual ICollection<ClaimSROI> ClaimSROIs { get; set; }
        public virtual ICollection<Medical> Medicals { get; set; }
        public virtual refTypeOfLoss refTypeOfLoss { get; set; }
        public virtual ICollection<ClaimCreditMemo> ClaimCreditMemoes { get; set; }
        public virtual ICollection<ClaimViewPermission> ClaimViewPermissions { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ReinsurerClaim> ReinsurerClaims { get; set; }
        public virtual ICollection<ClaimantNote> ClaimantNotes { get; set; }
        public virtual ICollection<ClaimantPhoto> ClaimantPhotoes { get; set; }
        public virtual ICollection<ClaimActivityLog> ClaimActivityLogs { get; set; }
        public virtual ICollection<FolderStructure> FolderStructures { get; set; }
        public virtual ICollection<FolderStructure> FolderStructures1 { get; set; }
        public virtual ICollection<FolderStructure> FolderStructures2 { get; set; }
        public virtual ICollection<ClaimCoverage> ClaimCoverages { get; set; }
        public virtual ICollection<ICD10Codes> ICD10Codes { get; set; }
        public virtual ICollection<ClaimDiary> ClaimDiaries { get; set; }
        public virtual ICollection<ClaimantDetail> ClaimantDetails { get; set; }
        public virtual ICollection<ClaimEmail> ClaimEmails { get; set; }
        public virtual ICollection<LegalContact> LegalContacts { get; set; }
        public virtual ICollection<ClaimEmployerDetail> ClaimEmployerDetails { get; set; }
        public virtual ICollection<LienHolder> LienHolders { get; set; }
        public virtual Insured Insured { get; set; }
        public virtual ICollection<ClaimLegal> ClaimLegals { get; set; }
        public virtual ClientBranch ClientBranch { get; set; }
        public virtual ClientBillingProfile ClientBillingProfile { get; set; }
        public virtual XactAnalysi XactAnalysi { get; set; }
        public virtual ICollection<ClaimDocument> ClaimDocuments { get; set; }
        public virtual ICollection<ClaimPhoto> ClaimPhotoes { get; set; }
        public virtual ICollection<ClaimWriteCheck> ClaimWriteChecks { get; set; }
        public virtual ICollection<ClaimLossTotal> ClaimLossTotals { get; set; }
        public virtual ICollection<ClaimReserve> ClaimReserves { get; set; }
        public virtual ICollection<Section111Detail> Section111Detail { get; set; }
    }
}
